services:
  tmserver:
    build:
      context: .
      args:
        SERVER_NAME: "Trackmania Server"
        SERVER_DESC: "This is a Trackmania Server"
        SERVER_SA_PASSWORD: "SuperAdmin"
        SERVER_ADM_PASSWORD: "Admin"
    container_name: tmserver
    restart: unless-stopped
    ports:
      - "2350:2350/tcp"
      - "2350:2350/udp"
      - "3450:3450/tcp"
      - "5000:5000/tcp"
      - "80:80/tcp"
    environment:
      - SERVER_NAME=Trackmania Server
      - SERVER_DESC=This is a Trackmania Server
      - SERVER_SA_PASSWORD=SuperAdmin
      - SERVER_ADM_PASSWORD=Admin
      - SERVER_MODE=internet
      - SERVER_LOGIN=
      - SERVER_VALIDATION_KEY=
    networks:
      tmserver_net:
        ipv4_address: 172.20.60.10

networks:
  tmserver_net:
    name: tmserver.dockernetwork.local
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.60.0/25
          gateway: 172.20.60.1
          ip_range: 172.20.60.64/26
