services:
  tmserver:
    build:
      context: .
      args:
        SERVER_NAME: "Trackmania Server"
        SERVER_DESC: "This is a Trackmania Server"
        SERVER_SA_PASSWORD: "SuperAdmin"
        SERVER_ADM_PASSWORD: "Admin"
    container_name: tmserver
    restart: unless-stopped
    ports:
      - "2350:2350/tcp"
      - "2350:2350/udp"
      - "3450:3450/tcp"
      - "5000:5000/tcp"
      - "80:80/tcp"
    environment:
      - SERVER_NAME=Trackmania Server
      - SERVER_DESC=This is a Trackmania Server
      - SERVER_SA_PASSWORD=SuperAdmin
      - SERVER_ADM_PASSWORD=Admin
      - SERVER_MODE=internet
      - SERVER_LOGIN=
      - SERVER_VALIDATION_KEY=
